package internat.db.chaternat;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ANSWER.
 */
public class Answer {

    private Long id;
    private String text;
    private String letter;
    private Boolean solution;
    private Long questionId;

    // KEEP FIELDS - put your custom fields here
    public static final String ANSWER_A = "a";
    public static final String ANSWER_B = "b";
    public static final String ANSWER_C = "c";
    public static final String ANSWER_D = "d";
    public static final String ANSWER_E = "e";
    // KEEP FIELDS END

    public Answer() {
    }

    public Answer(Long id) {
        this.id = id;
    }

    public Answer(Long id, String text, String letter, Boolean solution, Long questionId) {
        this.id = id;
        this.text = text;
        this.letter = letter;
        this.solution = solution;
        this.questionId = questionId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getLetter() {
        return letter;
    }

    public void setLetter(String letter) {
        this.letter = letter;
    }

    public Boolean getSolution() {
        return solution;
    }

    public void setSolution(Boolean solution) {
        this.solution = solution;
    }

    public Long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
